### ISSUE TITLE
应用程序bug

### ISSUE THREAD

**Issue by deepwebhacker** [teamdArk5/FscanParser#1]
![QQ截图20240827132536](https://github.com/user-attachments/assets/3a651af9-e940-469a-b740-b5b27b4daf16)
![QQ截图20240827132536](https://github.com/user-attachments/assets/7a304500-1b1e-49c5-91a3-b8cd24c14d97)

**Comment by teamdArk5** [comment]
能把你的这个文件去敏后发我吗？

**Comment by teamdArk5** [comment]
已经复现并修复，如若再有敬请回复。
