### ISSUE TITLE
Postgresql数据库弱口令未显示在WeakPass菜单下

### ISSUE THREAD

**Issue by asdascac** [teamdArk5/FscanParser#3]
Postgresql数据库弱口令未显示在WeakPass菜单下

**Comment by asdascac** [comment]
![image](https://github.com/user-attachments/assets/f8221b8b-9584-4929-ad9b-c5a4be4d9563)
![image](https://github.com/user-attachments/assets/4e63ddb4-d3c1-4abc-914a-7360632e68b1)

**Comment by teamdArk5** [comment]
你好，感谢提交！
根据你图中结果来看，你应该不是使用最新版的fscan吧？

**Comment by asdascac** [comment]
不是最新的fscan，是1.8版本

**Comment by teamdArk5** [comment]
下次用最新版（1.8.4）即可，旧版的结果跟新版结果稍有不同。
